version: "3.8"

services: 
################################################ 
#######Tengine      
    tengine:
        image: ${DOCKER_USER}/tengine
        build:
          context: ./tengine
          args:
            - TENGINE_VERSION=2.3.3
#######PHP7.1-FPM 
    php-7.1-fpm:
        image: ${DOCKER_USER}/php:7.1-fpm
        build:
          context: ./php
          args:
            - PHP_VERSION=7.1
            - FPM_OR_CLI=fpm
            - DEBIAN_RELEASE=buster
            - CHANGE_SOURCE=true
            - INSTALL_IMAGEMAGICK=true
            - INSTALL_SWOOLE=false
            - INSTALL_XDEBUG=true
            - INSTALL_XHPROF=false            
#######PHP7.3-FPM  
    php-7.3-fpm:
        image: ${DOCKER_USER}/php:7.3-fpm
        build:
          context: ./php
          args:
            - PHP_VERSION=7.3
            - FPM_OR_CLI=fpm
            - DEBIAN_RELEASE=buster
            - CHANGE_SOURCE=true
            - INSTALL_IMAGEMAGICK=true
            - INSTALL_SWOOLE=false
            - INSTALL_XDEBUG=true
            - INSTALL_XHPROF=false 
#######PHP7.4-FPM    
    php-7.4-fpm:
        image: ${DOCKER_USER}/php:7.4-fpm
        build:
          context: ./php
          args:
            - PHP_VERSION=7.4
            - FPM_OR_CLI=fpm
            - DEBIAN_RELEASE=
            - CHANGE_SOURCE=true
            - INSTALL_IMAGEMAGICK=true
            - INSTALL_SWOOLE=false
            - INSTALL_XDEBUG=true
            - INSTALL_XHPROF=false
#######PHP8.2-FPM    
    php-8.2-fpm:
        image: ${DOCKER_USER}/php:8.2-fpm
        build:
          context: ./php
          args:
            - PHP_VERSION=8.2
            - FPM_OR_CLI=fpm
            - DEBIAN_RELEASE=bullseye
            - CHANGE_SOURCE=true
            - INSTALL_IMAGEMAGICK=true
            - INSTALL_SWOOLE=false
            - INSTALL_XDEBUG=true
            - INSTALL_XHPROF=false            
### PHP-CLI ########################################  
#######PHP7.1-CLI
    php-7.1-cli:
        image: ${DOCKER_USER}/php:7.1-cli
        build:
          context: ./php
          args:
            - PHP_VERSION=7.1
            - FPM_OR_CLI=cli
            - DEBIAN_RELEASE=buster
            - CHANGE_SOURCE=true
            - INSTALL_IMAGEMAGICK=false
            - INSTALL_SWOOLE=true
            - INSTALL_XDEBUG=false
            - INSTALL_XHPROF=false
#######PHP7.4-CLI
    php-7.4-cli:
        image: ${DOCKER_USER}/php:7.4-cli
        build:
          context: ./php
          args:
            - PHP_VERSION=7.4
            - FPM_OR_CLI=cli
            - DEBIAN_RELEASE=buster
            - CHANGE_SOURCE=true
            - INSTALL_IMAGEMAGICK=true
            - INSTALL_SWOOLE=true
            - INSTALL_XDEBUG=false
            - INSTALL_XHPROF=false

#######PHP8.2-CLI
    php-8.2-cli:
        image: ${DOCKER_USER}/php:8.2-cli
        build:
          context: ./php
          args:
            - PHP_VERSION=8.2
            - FPM_OR_CLI=cli
            - DEBIAN_RELEASE=bullseye
            - CHANGE_SOURCE=true
            - INSTALL_IMAGEMAGICK=true
            - INSTALL_SWOOLE=true
            - INSTALL_XDEBUG=false
            - INSTALL_XHPROF=false
